### ISSUE TITLE
802.1X_FT auth key suite ends up being parsed (?) as 802.1X

### ISSUE THREAD

**Issue by solsticedhiver** [libwifi/libwifi#6] opened 2022-08-06 16:55 UTC
I am not sure of what I am seeing here, but it seems to me that, I don't know why, beacon frame with an Auth key Suites of 802.1X_FT (3) ends up being shown as 802.1X.

I found this because of my tests, but using the `examples/parse_beacon/parse_beacon.c` on the same .pcap file gives the same problem:

```
 $ ./parse_beacon/parse_beacon --file beacons.pcap
[...]
ESSID: DEMOWIFI
BSSID: 22:18:0a:6f:5a:ea
Receiver: ff:ff:ff:ff:ff:ff
Transmitter: 22:18:0a:6f:5a:ea
Channel: 11
WPS: No
Encryption: WPA2, WPA
	Group Ciphers: TKIP
	Pairwise Ciphers: TKIP, CCMP128
	Auth Key Suites: 802.1X
Tagged Parameters:
[...]
```
Shouldn't there be a **802.1X_FT** in Auth Key Suites line ?

[beacons.pcap.gz](https://github.com/libwifi/libwifi/files/9275453/beacons.pcap.gz)

**Comment by foxtrot** [comment] 2022-08-10 10:52
Thanks for reporting this. I've found the cause of the issue thanks to your pcap:

1) RSN information is decoded first, populating the `libwifi_bss` struct's fields with data that eventually allows `libwifi_get_auth_key_suites()` to fill a buffer with "802.1X, 802.1X_FT", which is working as intended.
![image](https://user-images.githubusercontent.com/4153572/183877483-a1fd1724-d55d-4989-b039-25d0a1a35db5.png)

2) The WPA information is decoded after this, due to the tag ordering (WPA is in a Microsoft Vendor tag (221) while RSN Information is it's own tag (48)
<img width="860" alt="image" src="https://user-images.githubusercontent.com/4153572/183877777-99064a36-0563-467f-9ea8-fdd817ca3711.png">

(Notice how this is a Mixed-mode WPA1/2 AP, indicated by both tags being present)

3) When the WPA information and RSN information are decoded, libwifi makes sure to unset WEP in `bss->encryption_info`:
```c
// src/parse/management/common.c
// Line 71 and 108
bss->encryption_info &= ~(unsigned int) WEP;
```

But when there are both WPA and RSN tags present, we can wind up clobbering the `encryption_info` field if WEP isn't present in the first place. This seems to be fixed by just checking before we do the operation:
```c
if (bss->encryption_info & WEP) {
    bss->encryption_info &= ~(unsigned int) WEP;
}
```
<img width="619" alt="image" src="https://user-images.githubusercontent.com/4153572/183883466-a436b3ec-866e-439d-b1cf-2948c49c7f99.png">

I'll push the fix shortly, and then bump the version.

**Comment by solsticedhiver** [comment] 2022-08-10 12:05
I would suggest to add tests to check for the correct parsing of packets;

In my soft, this is only for beacons, so that is relatively easy to do. I understand it will need a lot of more work here, depending of what you might want to test.

**Comment by foxtrot** [comment] 2022-08-10 18:17
There are tests, just not one for this specific handling.

**Closed** 2022-08-10 23:48 UTC
